// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { GetStaticPaths, GetStaticProps } from "next";
import { PlasmicOrgid } from "../../components/plasmic/shinkan_next/PlasmicOrgid";
import EventListItem from "../../components/EventListItem";
import { wpFetch } from "../../utils/wpFetch";
import useSWR from "swr";
import { useWPImage } from "../../hooks/useWPImage";
import Page from "../../components/Page";
import { Plasmic_404 } from "../../components/plasmic/shinkan_next/Plasmic_404";
import SocialLink from "../../components/SocialLink";
import { WPCarousel } from "../../components/WPCarousel";
import { activityType, organizationType } from "../../utils/categoryTable";
import { fallback } from "../../utils/config";
export const getStaticPaths: GetStaticPaths = async () => {
  const pages = await wpFetch("/v2/pages");

  const paths = pages.map((it: any) => ({
    params: {
      id: it.id.toString(),
    },
  }));
  return {
    paths,
    fallback: fallback,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const pageId = params?.id;
  const post = await wpFetch(`/v2/pages/${pageId}`);

  return {
    props: {
      initialData: post,
    } as Props,
  };
};
type Props = {
  initialData: any;
};
function Orgid({ initialData }: Props) {
  const router = useRouter();
  if (router.isFallback) {
    console.log("フォールバックにつきフェッチします");
  }
  const pageId = router.query.id;
  const { data, error } = useSWR(`/v2/pages/${pageId}`, wpFetch, {
    initialData,
  });
  if (data?.data?.status === 404) {
    return <Plasmic_404 />;
  }
  if (error) {
    console.error("page error", error);
    return (
      <Page>
        <>エラー</>
      </Page>
    );
  }
  if (!data?.title) {
    return (
      <Page>
        <>読み込み中</>
      </Page>
    );
  }
  const title = data.title.rendered;
  const description = data.excerpt.rendered.replace(/<[^>]*>?/gm, "");
  const url = `/org/${pageId}`;
  const mainImage = useWPImage(data.event.mainImage[0], "medium");
  const events = (() => {
    const arr = [];
    const len = data.event.title.length;
    for (let i = 0; i < len; i++) {
      arr.push({
        start: data.event.start[i],
        end: data.event.end[i],
        title: data.event.title[i],
        description: data.event.description[i],
      });
    }
    return arr;
  })();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:type" content="blog" />
        <meta property="og:url" content={url} />
        <meta property="og:image" content={mainImage} />
        <meta property="og:site_name" content={title} />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@tsukuba_shinkan" />
        <meta name="twitter:url" content={url} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={mainImage} />
        <link rel="canonical" href={url} />
      </Head>
      <PlasmicOrgid
        orgType={organizationType[data.organizationtype[0]].name as any}
        activity={activityType[data.activitytype[0]].name as any}
        image={
          <WPCarousel
            mainImage={data.event.mainImage[0]}
            otherImages={data.event.otherImages}
            youtubeLinks={data.event.youtubeLinks}
          ></WPCarousel>
        }
        events={events.map((e: any, i: number) => (
          <EventListItem
            eventTitle={e.title}
            dateTime={`${e.start} - ${e.end}`}
            key={i}
          >
            <div
              dangerouslySetInnerHTML={{
                __html: e.description, // WordPressが無害化してくれると期待しているので危ないことしても許されると思っています。
              }}
              className="wpRendered"
            />
          </EventListItem>
        ))}
        title={title}
        socialLinks={
          <>
            {data.event.url?.[0] && (
              <SocialLink
                label={data.event.url[0]}
                type="url"
                href={data.event.url[0]}
              />
            )}
            {data.event.twitter?.[0] && (
              <SocialLink
                label={"@" + data.event.twitter[0]}
                type="twitter"
                href={"https://twitter.com/" + data.event.twitter[0]}
              />
            )}
            {data.event.instagram?.[0] && (
              <SocialLink
                label={data.event.instagram[0]}
                type="twitter"
                href={"https://www.instagram.com/" + data.event.instagram[0]}
              />
            )}
          </>
        }
      >
        <div
          dangerouslySetInnerHTML={{
            __html: data.content.rendered, // WordPressが無害化してくれると期待しているので危ないことしても許されると思っています。
          }}
          className="wpRendered"
        />
      </PlasmicOrgid>
    </>
  );
}

export default Orgid;
