// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicOnlyOpencampus,
  DefaultOnlyOpencampusProps,
} from "./plasmic/shinkan_next/PlasmicOnlyOpencampus";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { isOpencanpus } from "../utils/config";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface OnlyOpencampusProps extends Omit<DefaultOnlyOpencampusProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultOnlyOpencampusProps altogether and have
// total control over the props for your component.
interface OnlyOpencampusProps extends DefaultOnlyOpencampusProps {}

function OnlyOpencampus_(
  props: OnlyOpencampusProps,
  ref: HTMLElementRefOf<"div">
) {
  return (
    <PlasmicOnlyOpencampus
      root={{ ref }}
      {...props}
      opencampus={isOpencanpus}
    />
  );
}

const OnlyOpencampus = React.forwardRef(OnlyOpencampus_);
export default OnlyOpencampus;
