// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React from "react";
import { useWPImage } from "../hooks/useWPImage";
import { useOrgList } from "./OrgList";
import {
  PlasmicOrgCard,
  DefaultOrgCardProps,
} from "./plasmic/shinkan_next/PlasmicOrgCard";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface OrgCardProps extends Omit<DefaultOrgCardProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultOrgCardProps altogether and have
// total control over the props for your component.
interface OrgCardProps extends DefaultOrgCardProps {
  orgId: number;
  src?: string;
  wpsrc?: string;
  name: string;
  activity: "sports" | "art" | "culture" | "other";
  orgType: "ippan" | "kagai" | "other";
  description: string;
}

function OrgCard(props: OrgCardProps) {
  const { list } = useOrgList();
  const transProps = {
    name: props.name,
    activity: props.activity,
    orgType: props.orgType,
    src: props.src,
  };
  let src;
  if (props.wpsrc) {
    src = useWPImage(props.wpsrc, "medium");
  } else {
    src = props.src;
  }
  return (
    <PlasmicOrgCard
      {...transProps}
      to={`/org/${props.orgId}`}
      description={
        <div
          dangerouslySetInnerHTML={{
            __html: props.description, // WordPressが無害化してくれると期待しているので危ないことしても許されると思っています。
          }}
        ></div>
      }
      list={list}
    >
      <div
        className="org-card-bg"
        style={{
          backgroundImage: `url(${src})`,
          opacity: src ? 1 : 0,
        }}
      ></div>
    </PlasmicOrgCard>
  );
}

export default OrgCard;
