// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPage,
  DefaultPageProps,
} from "./plasmic/shinkan_next/PlasmicPage";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface PageProps extends Omit<DefaultPageProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPageProps altogether and have
// total control over the props for your component.
interface PageProps extends DefaultPageProps {}

function Page(props: PageProps) {
  return <PlasmicPage {...props} />;
}

export default Page;
