// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4oWAtwkSeL4ciDYEekjxG9
// Component: ErjPU3ASyU
import * as React from "react";

import __PlatformHead from "next/head";
import __PlatformLink, { LinkProps as __PlatformLinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Page from "../../Page"; // plasmic-import: tdmoFHXXat7/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_shinkan_next.module.css"; // plasmic-import: 4oWAtwkSeL4ciDYEekjxG9/projectcss
import * as sty from "./PlasmicAnnouncement.module.css"; // plasmic-import: ErjPU3ASyU/css

export type PlasmicAnnouncement__VariantMembers = {};

export type PlasmicAnnouncement__VariantsArgs = {};
type VariantPropType = keyof PlasmicAnnouncement__VariantsArgs;
export const PlasmicAnnouncement__VariantProps = new Array<VariantPropType>();

export type PlasmicAnnouncement__ArgsType = {};
type ArgPropType = keyof PlasmicAnnouncement__ArgsType;
export const PlasmicAnnouncement__ArgProps = new Array<ArgPropType>();

export type PlasmicAnnouncement__OverridesType = {
  root?: p.Flex<"div">;
  page?: p.Flex<typeof Page>;
};

export interface DefaultAnnouncementProps {
  className?: string;
}

function PlasmicAnnouncement__RenderFunc(props: {
  variants: PlasmicAnnouncement__VariantsArgs;
  args: PlasmicAnnouncement__ArgsType;
  overrides: PlasmicAnnouncement__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <__PlatformHead>
        <title key="title">{""}</title>
      </__PlatformHead>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Page
            data-plasmic-name={"page"}
            data-plasmic-override={overrides.page}
            className={classNames("__wab_instance", sty.page)}
            container={
              <React.Fragment>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__gyFq8
                  )}
                >
                  {"お知らせ"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__fjhVu
                  )}
                >
                  {"新歓Webを公開しました"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___97Osx
                  )}
                >
                  {"2020/4/1"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__bKa9P
                  )}
                >
                  {"テキストがWordPressから取得されると思います"}
                </div>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "page"],
  page: ["page"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  page: typeof Page;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAnnouncement__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicAnnouncement__VariantsArgs;
  args?: PlasmicAnnouncement__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicAnnouncement__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicAnnouncement__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAnnouncement__ArgProps,
      internalVariantPropNames: PlasmicAnnouncement__VariantProps
    });

    return PlasmicAnnouncement__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAnnouncement";
  } else {
    func.displayName = `PlasmicAnnouncement.${nodeName}`;
  }
  return func;
}

export const PlasmicAnnouncement = Object.assign(
  // Top-level PlasmicAnnouncement renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    page: makeNodeComponent("page"),

    // Metadata about props expected for PlasmicAnnouncement
    internalVariantProps: PlasmicAnnouncement__VariantProps,
    internalArgProps: PlasmicAnnouncement__ArgProps
  }
);

export default PlasmicAnnouncement;
/* prettier-ignore-end */
