// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4oWAtwkSeL4ciDYEekjxG9
// Component: eUF7R_7Fga
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Page from "../../Page"; // plasmic-import: tdmoFHXXat7/component
import OnlyOpencampus from "../../OnlyOpencampus"; // plasmic-import: x1nR8p_T71/component
import EventListItem from "../../EventListItem"; // plasmic-import: GMIuDj3rjM/component
import CategoryRadio from "../../CategoryRadio"; // plasmic-import: s14nWegQm7/component
import OrgList from "../../OrgList"; // plasmic-import: LzatSZ7oBYe/component
import OrgCard from "../../OrgCard"; // plasmic-import: hH2h_5Dtgs/component
import OnlyShinkan from "../../OnlyShinkan"; // plasmic-import: wOiDfdBxT1/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_shinkan_next.module.css"; // plasmic-import: 4oWAtwkSeL4ciDYEekjxG9/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: eUF7R_7Fga/css

import EventNoteBlack24DpsvgIcon from "./icons/PlasmicIcon__EventNoteBlack24Dpsvg"; // plasmic-import: NP9EaMgoaE/icon
import SearchBlack24DpsvgIcon from "./icons/PlasmicIcon__SearchBlack24Dpsvg"; // plasmic-import: C2oaTY0g2i/icon

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {
  orgs?: React.ReactNode;
  categoryRadio?: React.ReactNode;
  eventList?: React.ReactNode;
  news?: React.ReactNode;
  eventCount?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>(
  "orgs",
  "categoryRadio",
  "eventList",
  "news",
  "eventCount"
);

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  page?: p.Flex<typeof Page>;
  hero?: p.Flex<"div">;
  onlyOpencampus?: p.Flex<typeof OnlyOpencampus>;
  description?: p.Flex<"div">;
  events?: p.Flex<"div">;
  button?: p.Flex<"div">;
  eventList?: p.Flex<"div">;
  orgsContainer?: p.Flex<"div">;
  orgList?: p.Flex<typeof OrgList>;
  onlyShinkan?: p.Flex<typeof OnlyShinkan>;
  announcements?: p.Flex<"div">;
  eventList2?: p.Flex<"div">;
};

export interface DefaultHomeProps {}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Page
            data-plasmic-name={"page"}
            data-plasmic-override={overrides.page}
            className={classNames("__wab_instance", sty.page)}
          >
            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__ig9Yl)} />

              <div className={classNames(projectcss.all, sty.freeBox__ykPs0)} />
            </div>

            <OnlyOpencampus
              data-plasmic-name={"onlyOpencampus"}
              data-plasmic-override={overrides.onlyOpencampus}
              className={classNames("__wab_instance", sty.onlyOpencampus)}
            >
              {true ? (
                <div
                  data-plasmic-name={"description"}
                  data-plasmic-override={overrides.description}
                  className={classNames(projectcss.all, sty.description)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jdzaq
                    )}
                  >
                    {
                      "筑波大学のオンラインオープンキャンパスへようこそ！\nこのサイトは受験生のみなさんに、筑波大学のサークルや部活動など（課外活動団体・一般学生団体）を知っていただくために開設しました。筑波大学の雰囲気を知ることや、気になるサークル・部活探し、勉強の合間の息抜き…などにご活用ください！\n（掲載団体によっては、一部在学生向けの情報が含まれることがあります。ご注意ください。）"
                    }
                  </div>
                </div>
              ) : null}
            </OnlyOpencampus>

            <div
              data-plasmic-name={"events"}
              data-plasmic-override={overrides.events}
              className={classNames(projectcss.all, sty.events)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__p08Hk)}>
                <EventNoteBlack24DpsvgIcon
                  className={classNames(projectcss.all, sty.svg__r5Oqd)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vzmTl
                  )}
                >
                  {"本日のイベント"}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__lxuSy)}>
                  {p.renderPlasmicSlot({
                    defaultContents: "4",
                    value: args.eventCount,
                    className: classNames(sty.slotTargetEventCount)
                  })}
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox__kKcvo)}
                />

                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(projectcss.all, sty.button)}
                >
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__mV3YJ
                    )}
                    component={Link}
                    href={"/events" as const}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dUeh5
                      )}
                    >
                      {"イベント検索へ"}
                    </div>

                    <SearchBlack24DpsvgIcon
                      className={classNames(projectcss.all, sty.svg__uJgVa)}
                      role={"img"}
                    />
                  </p.PlasmicLink>
                </div>
              </div>

              <div
                data-plasmic-name={"eventList"}
                data-plasmic-override={overrides.eventList}
                className={classNames(projectcss.all, sty.eventList)}
              >
                {p.renderPlasmicSlot({
                  defaultContents: (
                    <React.Fragment>
                      <EventListItem
                        className={classNames(
                          "__wab_instance",
                          sty.eventListItem__hoLhM
                        )}
                        eventTitle={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___1Nq1
                            )}
                          >
                            {"桜を見る会 @ 反町の森公園"}
                          </div>
                        }
                      />

                      <EventListItem
                        className={classNames(
                          "__wab_instance",
                          sty.eventListItem__av7V1
                        )}
                        eventTitle={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vcY8
                            )}
                          >
                            {"橋本環奈同好会オンライン説明会"}
                          </div>
                        }
                      />

                      <EventListItem
                        className={classNames(
                          "__wab_instance",
                          sty.eventListItem__bTwts
                        )}
                        eventTitle={"女装同好会"}
                      />

                      <EventListItem
                        className={classNames(
                          "__wab_instance",
                          sty.eventListItem__svl9R
                        )}
                      />
                    </React.Fragment>
                  ),
                  value: args.eventList
                })}
              </div>
            </div>

            <div
              data-plasmic-name={"orgsContainer"}
              data-plasmic-override={overrides.orgsContainer}
              className={classNames(projectcss.all, sty.orgsContainer)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__gJi0C)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7SGb5
                  )}
                >
                  {"おすすめの団体"}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__bkJeC)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___4Coe3)}
                  >
                    {p.renderPlasmicSlot({
                      defaultContents: (
                        <React.Fragment>
                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__l6S0E
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__soEt
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__bFw1X
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__fWiFb
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__wqPyK
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio__rEtQa
                            )}
                          />

                          <CategoryRadio
                            className={classNames(
                              "__wab_instance",
                              sty.categoryRadio___2VI6B
                            )}
                          />
                        </React.Fragment>
                      ),
                      value: args.categoryRadio
                    })}
                  </div>
                </div>
              </div>

              <OrgList
                data-plasmic-name={"orgList"}
                data-plasmic-override={overrides.orgList}
                className={classNames("__wab_instance", sty.orgList)}
              >
                {p.renderPlasmicSlot({
                  defaultContents: (
                    <React.Fragment>
                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__tFQfL
                        )}
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__kHx23
                        )}
                        description={"アクセスするたび変わります"}
                        list={true}
                        name={"女装同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__gSKea
                        )}
                        description={"ランダムに変わります"}
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__dw2EO
                        )}
                        description={
                          "ランダムに選ぶ機能はWordPressの機能を使いたいところですが"
                        }
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__nyZ9J
                        )}
                        description={
                          "おそらくフロントエンドでシャッフルしないといけない"
                        }
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__k2DJn
                        )}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6Dhj
                            )}
                          >
                            {
                              "長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れ長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみようてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう長い文字を入れてみよう"
                            }
                          </div>
                        }
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard___7IDo0
                        )}
                        list={true}
                        name={"橋本環奈同好会"}
                      />

                      <OrgCard
                        className={classNames(
                          "__wab_instance",
                          sty.orgCard__jXEn
                        )}
                        list={true}
                      />
                    </React.Fragment>
                  ),
                  value: args.orgs
                })}
              </OrgList>

              <div className={classNames(projectcss.all, sty.freeBox__c6Wud)}>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__xXnx
                  )}
                  component={Link}
                  href={"/org" as const}
                  platform={"nextjs"}
                >
                  {"団体を検索する"}
                </p.PlasmicLink>
              </div>
            </div>

            <OnlyShinkan
              data-plasmic-name={"onlyShinkan"}
              data-plasmic-override={overrides.onlyShinkan}
              className={classNames("__wab_instance", sty.onlyShinkan)}
            >
              <div
                data-plasmic-name={"announcements"}
                data-plasmic-override={overrides.announcements}
                className={classNames(projectcss.all, sty.announcements)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__gLaDz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ruukh
                    )}
                  >
                    {"お知らせ"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"eventList2"}
                  data-plasmic-override={overrides.eventList2}
                  className={classNames(projectcss.all, sty.eventList2)}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: (
                      <EventListItem
                        className={classNames(
                          "__wab_instance",
                          sty.eventListItem__npZl
                        )}
                        eventTitle={"a"}
                      />
                    ),

                    value: args.news
                  })}
                </div>
              </div>
            </OnlyShinkan>
          </Page>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "page",
    "hero",
    "onlyOpencampus",
    "description",
    "events",
    "button",
    "eventList",
    "orgsContainer",
    "orgList",
    "onlyShinkan",
    "announcements",
    "eventList2"
  ],
  page: [
    "page",
    "hero",
    "onlyOpencampus",
    "description",
    "events",
    "button",
    "eventList",
    "orgsContainer",
    "orgList",
    "onlyShinkan",
    "announcements",
    "eventList2"
  ],
  hero: ["hero"],
  onlyOpencampus: ["onlyOpencampus", "description"],
  description: ["description"],
  events: ["events", "button", "eventList"],
  button: ["button"],
  eventList: ["eventList"],
  orgsContainer: ["orgsContainer", "orgList"],
  orgList: ["orgList"],
  onlyShinkan: ["onlyShinkan", "announcements", "eventList2"],
  announcements: ["announcements", "eventList2"],
  eventList2: ["eventList2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  page: typeof Page;
  hero: "div";
  onlyOpencampus: typeof OnlyOpencampus;
  description: "div";
  events: "div";
  button: "div";
  eventList: "div";
  orgsContainer: "div";
  orgList: typeof OrgList;
  onlyShinkan: typeof OnlyShinkan;
  announcements: "div";
  eventList2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    page: makeNodeComponent("page"),
    hero: makeNodeComponent("hero"),
    onlyOpencampus: makeNodeComponent("onlyOpencampus"),
    description: makeNodeComponent("description"),
    events: makeNodeComponent("events"),
    button: makeNodeComponent("button"),
    eventList: makeNodeComponent("eventList"),
    orgsContainer: makeNodeComponent("orgsContainer"),
    orgList: makeNodeComponent("orgList"),
    onlyShinkan: makeNodeComponent("onlyShinkan"),
    announcements: makeNodeComponent("announcements"),
    eventList2: makeNodeComponent("eventList2"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
