// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4oWAtwkSeL4ciDYEekjxG9
// Component: tdmoFHXXat7
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import OnlyOpencampus from "../../OnlyOpencampus"; // plasmic-import: x1nR8p_T71/component
import OnlyShinkan from "../../OnlyShinkan"; // plasmic-import: wOiDfdBxT1/component
import HeaderLink from "../../HeaderLink"; // plasmic-import: gugJhCOlow/component

import { useScreenVariants as useScreenVariantsrGlYl5PrqxJp } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: rGlYl5prqxJP/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_shinkan_next.module.css"; // plasmic-import: 4oWAtwkSeL4ciDYEekjxG9/projectcss
import sty from "./PlasmicPage.module.css"; // plasmic-import: tdmoFHXXat7/css

import EventNoteBlack24DpsvgIcon from "./icons/PlasmicIcon__EventNoteBlack24Dpsvg"; // plasmic-import: NP9EaMgoaE/icon
import SearchBlack24DpsvgIcon from "./icons/PlasmicIcon__SearchBlack24Dpsvg"; // plasmic-import: C2oaTY0g2i/icon

export type PlasmicPage__VariantMembers = {};

export type PlasmicPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicPage__VariantsArgs;
export const PlasmicPage__VariantProps = new Array<VariantPropType>();

export type PlasmicPage__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPage__ArgsType;
export const PlasmicPage__ArgProps = new Array<ArgPropType>("children");

export type PlasmicPage__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<"div">;
  title?: p.Flex<"a"> & Partial<LinkProps>;
  onlyOpencampus?: p.Flex<typeof OnlyOpencampus>;
  onlyShinkan?: p.Flex<typeof OnlyShinkan>;
  links?: p.Flex<"div">;
  container?: p.Flex<"div">;
  footer?: p.Flex<"div">;
  columns?: p.Flex<"div">;
};

export interface DefaultPageProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicPage__RenderFunc(props: {
  variants: PlasmicPage__VariantsArgs;
  args: PlasmicPage__ArgsType;
  overrides: PlasmicPage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrGlYl5PrqxJp()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__i8QZa)}>
        <div
          data-plasmic-name={"header"}
          data-plasmic-override={overrides.header}
          className={classNames(projectcss.all, sty.header)}
        >
          <p.PlasmicLink
            data-plasmic-name={"title"}
            data-plasmic-override={overrides.title}
            className={classNames(projectcss.all, projectcss.a, sty.title)}
            component={Link}
            href={"/" as const}
            platform={"nextjs"}
          >
            <img
              alt={""}
              className={classNames(
                projectcss.all,
                projectcss.img,
                sty.img__e1Q90
              )}
              src={"/plasmic/shinkan_next/images/microsoftTeamsImagepng.png"}
            />

            <OnlyOpencampus
              data-plasmic-name={"onlyOpencampus"}
              data-plasmic-override={overrides.onlyOpencampus}
              className={classNames("__wab_instance", sty.onlyOpencampus)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gyEx
                )}
              >
                {"筑波大学 サークル・部活動紹介"}
              </div>
            </OnlyOpencampus>

            <OnlyShinkan
              data-plasmic-name={"onlyShinkan"}
              data-plasmic-override={overrides.onlyShinkan}
              className={classNames("__wab_instance", sty.onlyShinkan)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__enS97
                )}
              >
                {"筑波大学新歓Web"}
              </div>
            </OnlyShinkan>
          </p.PlasmicLink>

          <div
            data-plasmic-name={"links"}
            data-plasmic-override={overrides.links}
            className={classNames(projectcss.all, sty.links)}
          >
            <HeaderLink
              className={classNames("__wab_instance", sty.headerLink___2GQ6)}
              to={"/events" as const}
            >
              <EventNoteBlack24DpsvgIcon
                className={classNames(projectcss.all, sty.svg__aWkPc)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wyzrt
                )}
              >
                {"イベントを探す"}
              </div>
            </HeaderLink>

            <HeaderLink
              className={classNames("__wab_instance", sty.headerLink__lle4C)}
              to={"/org" as const}
            >
              <SearchBlack24DpsvgIcon
                className={classNames(projectcss.all, sty.svg___9RFzq)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wyBgt
                )}
              >
                {"団体を探す"}
              </div>
            </HeaderLink>
          </div>
        </div>

        <div
          data-plasmic-name={"container"}
          data-plasmic-override={overrides.container}
          className={classNames(projectcss.all, sty.container)}
        >
          {p.renderPlasmicSlot({
            defaultContents: null,
            value: args.children
          })}
        </div>

        <div
          data-plasmic-name={"footer"}
          data-plasmic-override={overrides.footer}
          className={classNames(projectcss.all, sty.footer)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column__swH9F)}>
              <div className={classNames(projectcss.all, sty.freeBox__uj51S)}>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__oM7U
                  )}
                  component={Link}
                  href={"/about" as const}
                  platform={"nextjs"}
                >
                  {"このサイトについて"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ur8FT
                  )}
                  component={Link}
                  href={
                    "https://www.stb.tsukuba.ac.jp/~shinkan-web/news/1437" as const
                  }
                  platform={"nextjs"}
                >
                  {"新歓祭について"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___8Ay0F
                  )}
                  component={Link}
                  href={"/404" as const}
                  platform={"nextjs"}
                >
                  {"団体用システムログイン"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__xFwV
                  )}
                  component={Link}
                  href={
                    "http://www.stb.tsukuba.ac.jp/~bunsa/wiki/doku.php" as const
                  }
                  platform={"nextjs"}
                >
                  {"文化系サークル連合会"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ilNgt
                  )}
                  component={Link}
                  href={"http://www.stb.tsukuba.ac.jp/~geisa/" as const}
                  platform={"nextjs"}
                >
                  {"芸術系サークル連合会"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__qr0Va
                  )}
                  component={Link}
                  href={"https://www.stb.tsukuba.ac.jp/~taiikukai/" as const}
                  platform={"nextjs"}
                >
                  {"体育会"}
                </p.PlasmicLink>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__yXJr8)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l1A9M
                )}
              >
                {"©\u00012021\u0001筑波大学新歓Webプロジェクトチーム"}
              </div>

              {false ? (
                <img
                  alt={""}
                  className={classNames(
                    projectcss.all,
                    projectcss.img,
                    sty.img__jxcc1
                  )}
                  src={"/plasmic/shinkan_next/images/schoollogopng.png"}
                />
              ) : null}
            </div>
          </p.Stack>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "title",
    "onlyOpencampus",
    "onlyShinkan",
    "links",
    "container",
    "footer",
    "columns"
  ],
  header: ["header", "title", "onlyOpencampus", "onlyShinkan", "links"],
  title: ["title", "onlyOpencampus", "onlyShinkan"],
  onlyOpencampus: ["onlyOpencampus"],
  onlyShinkan: ["onlyShinkan"],
  links: ["links"],
  container: ["container"],
  footer: ["footer", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  title: "a";
  onlyOpencampus: typeof OnlyOpencampus;
  onlyShinkan: typeof OnlyShinkan;
  links: "div";
  container: "div";
  footer: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPage__VariantsArgs;
    args?: PlasmicPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPage__ArgProps,
      internalVariantPropNames: PlasmicPage__VariantProps
    });

    return PlasmicPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPage";
  } else {
    func.displayName = `PlasmicPage.${nodeName}`;
  }
  return func;
}

export const PlasmicPage = Object.assign(
  // Top-level PlasmicPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    title: makeNodeComponent("title"),
    onlyOpencampus: makeNodeComponent("onlyOpencampus"),
    onlyShinkan: makeNodeComponent("onlyShinkan"),
    links: makeNodeComponent("links"),
    container: makeNodeComponent("container"),
    footer: makeNodeComponent("footer"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicPage
    internalVariantProps: PlasmicPage__VariantProps,
    internalArgProps: PlasmicPage__ArgProps
  }
);

export default PlasmicPage;
/* prettier-ignore-end */
