// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4oWAtwkSeL4ciDYEekjxG9
// Component: g0BBn2-YWf
import * as React from "react";

import __PlatformHead from "next/head";
import __PlatformLink, { LinkProps as __PlatformLinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_shinkan_next.module.css"; // plasmic-import: 4oWAtwkSeL4ciDYEekjxG9/projectcss
import * as sty from "./PlasmicEventListItem2.module.css"; // plasmic-import: g0BBn2-YWf/css

import ExpandMoreBlack24DpsvgIcon from "./icons/PlasmicIcon__ExpandMoreBlack24Dpsvg"; // plasmic-import: nktDh0ThKG/icon
import ExpandLess24PxsvgIcon from "./icons/PlasmicIcon__ExpandLess24Pxsvg"; // plasmic-import: PYIjxKxUq0/icon

export type PlasmicEventListItem2__VariantMembers = {
  expand: "expand";
  activity: "sports" | "art" | "culture" | "other";
};

export type PlasmicEventListItem2__VariantsArgs = {
  expand?: SingleBooleanChoiceArg<"expand">;
  activity?: SingleChoiceArg<"sports" | "art" | "culture" | "other">;
};

type VariantPropType = keyof PlasmicEventListItem2__VariantsArgs;
export const PlasmicEventListItem2__VariantProps = new Array<VariantPropType>(
  "expand",
  "activity"
);

export type PlasmicEventListItem2__ArgsType = {};
type ArgPropType = keyof PlasmicEventListItem2__ArgsType;
export const PlasmicEventListItem2__ArgProps = new Array<ArgPropType>();

export type PlasmicEventListItem2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultEventListItem2Props {
  expand?: SingleBooleanChoiceArg<"expand">;
  activity?: SingleChoiceArg<"sports" | "art" | "culture" | "other">;
  className?: string;
}

function PlasmicEventListItem2__RenderFunc(props: {
  variants: PlasmicEventListItem2__VariantsArgs;
  args: PlasmicEventListItem2__ArgsType;
  overrides: PlasmicEventListItem2__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(defaultcss.all, sty.box__luIu, {
          [sty.box__activity_art__luIuBzkut]: hasVariant(
            variants,
            "activity",
            "art"
          ),
          [sty.box__activity_culture__luIuBcQjz]: hasVariant(
            variants,
            "activity",
            "culture"
          ),
          [sty.box__activity_other__luIu3V2CT]: hasVariant(
            variants,
            "activity",
            "other"
          ),
          [sty.box__activity_sports__luIuVLebt]: hasVariant(
            variants,
            "activity",
            "sports"
          ),
          [sty.box__expand__luIuVeGt]: hasVariant(variants, "expand", "expand")
        })}
      >
        <div
          className={classNames(defaultcss.all, sty.box__cAelG, {
            [sty.box__activity_other__cAelG3V2CT]: hasVariant(
              variants,
              "activity",
              "other"
            ),
            [sty.box__activity_sports__cAelGvLebt]: hasVariant(
              variants,
              "activity",
              "sports"
            ),
            [sty.box__expand__cAelGveGt]: hasVariant(
              variants,
              "expand",
              "expand"
            )
          })}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__wkg,
              {
                [sty.box__activity_other__wkg3V2CT]: hasVariant(
                  variants,
                  "activity",
                  "other"
                )
              }
            )}
          >
            {"4/4 18:00"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__aTUjn,
              {
                [sty.box__expand__aTUjnVeGt]: hasVariant(
                  variants,
                  "expand",
                  "expand"
                )
              }
            )}
          >
            {"ご飯会"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__epzFf
            )}
          >
            {"Zoom"}
          </div>

          <div className={classNames(defaultcss.all, sty.box___46Hq2)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___2DfeI,
                {
                  [sty.box__activity_other___2DfeI3V2CT]: hasVariant(
                    variants,
                    "activity",
                    "other"
                  )
                }
              )}
            >
              {"ちょっと長めの団体名を入れてみます"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__keKdP
              )}
            >
              {"体育系・一般学生団体"}
            </div>
          </div>

          <p.PlasmicIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            PlasmicIconType={
              hasVariant(variants, "expand", "expand")
                ? ExpandLess24PxsvgIcon
                : ExpandMoreBlack24DpsvgIcon
            }
            className={classNames(defaultcss.all, sty.svg, {
              [sty.svg__expand]: hasVariant(variants, "expand", "expand")
            })}
            role={"img"}
          />
        </div>

        {(hasVariant(variants, "expand", "expand") ? true : false) ? (
          <div
            className={classNames(defaultcss.all, sty.box__n0Ou2, {
              [sty.box__expand__n0Ou2VeGt]: hasVariant(
                variants,
                "expand",
                "expand"
              )
            })}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___3Kcnf,
                {
                  [sty.box__expand___3KcnfVeGt]: hasVariant(
                    variants,
                    "expand",
                    "expand"
                  )
                }
              )}
            >
              {"詳細情報がここに書いてあります"}
            </div>
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEventListItem2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicEventListItem2__VariantsArgs;
  args?: PlasmicEventListItem2__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicEventListItem2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicEventListItem2__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicEventListItem2__ArgProps,
      internalVariantPropNames: PlasmicEventListItem2__VariantProps
    });

    return PlasmicEventListItem2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEventListItem2";
  } else {
    func.displayName = `PlasmicEventListItem2.${nodeName}`;
  }
  return func;
}

export const PlasmicEventListItem2 = Object.assign(
  // Top-level PlasmicEventListItem2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicEventListItem2
    internalVariantProps: PlasmicEventListItem2__VariantProps,
    internalArgProps: PlasmicEventListItem2__ArgProps
  }
);

export default PlasmicEventListItem2;
/* prettier-ignore-end */
