// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicNewsid } from "../../components/plasmic/shinkan_next/PlasmicNewsid";

function Newsid() {
  return <PlasmicNewsid />;
}

export default Newsid;
