// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicAbout } from "../components/plasmic/shinkan_next/PlasmicAbout";

function About() {
  // Use PlasmicAbout to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicAbout are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicAbout is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <PlasmicAbout>
      <p>
        このサイトは2021年度の新歓活動が新型コロナウイルスの影響により大幅に制限されることを受け、筑波大学Webページ学生委員会が中心となって製作しました。
        筑波大学内のサークル等の団体のポータルサイトとしてご活用いただければ幸いです。
      </p>
      <h2>オープンソース</h2>
      <p>
        このサイトの開発はオープンソースプロジェクトとして進められ、様々な方にご協力をいただきました。この場をお借りして感謝申し上げます。
        <br />
        GitHubリポジトリは
        <a
          href="https://github.com/tsukuba-shinkan/shinkan-next"
          target="_blank"
          rel="noopener noreferrer"
        >
          こちら
        </a>
      </p>
      <h2>Google Analyticsの利用について</h2>
      <p>
        このサイトでは、利用状況を把握し、サイトの改善につなげるためにGoogle
        Analyticsを使用しています。 Google
        AnalyticsではCookieを利用し、個人を特定する情報を含まない形でアクセス情報を収集しています。
      </p>
      <p>
        Google Analyticsでの個人情報の扱いについては
        <a
          href="https://support.google.com/analytics/answer/6004245?hl=ja"
          target="_blank"
          rel="noopener noreferrer"
        >
          Google社のサイト
        </a>
        をご覧ください。
      </p>
      <h2>お問い合わせ</h2>
      <p>
        このサイト全体に関するお問い合わせ（不具合等）はWebページ学生委員会（
        webgaku(at)stb.tsukuba.ac.jp
        ）、各コンテンツに関するお問い合わせは各団体の連絡先にお願いいたします。
      </p>
    </PlasmicAbout>
  );
}

export default About;
