// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHome } from "../components/plasmic/shinkan_next/PlasmicHome";

function Home() {
  return <PlasmicHome />;
}

export default Home;
