// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState, useEffect } from "react";
import OrgCard from "../components/OrgCard";
import Pager from "../components/Pager";
import { PlasmicOrg } from "../components/plasmic/shinkan_next/PlasmicOrg";
import { activityType, organizationType } from "../utils/categoryTable";
import { buildPathWithWPQuery, wpFetch } from "../utils/wpFetch";

const PER_PAGE = 1;

function Org() {
  // Use PlasmicOrg to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicOrg are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicOrg is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  const [orgs, setOrgs] = useState<
    {
      wpsrc: string;
      description: string;
      name: string;
      activity: "sports" | "art" | "culture" | "other";
      orgType: "ippan" | "kagai" | "other";
      orgId: number;
    }[]
  >([]);
  const [page, setPage] = useState(1); // one based index
  useEffect(() => {
    search();
  }, [page]);

  const [keyword, setKeyword] = useState("");
  const search = async () => {
    if (keyword.length === 0) {
      return setOrgs([]);
    }
    const result = await wpFetch(
      buildPathWithWPQuery("/v2/pages", {
        search: keyword,
        per_page: PER_PAGE.toString(),
        page: page.toString(),
        _fields:
          "id,date,modified,title,title,content,excerpt,author,activitytype,organizationtype,event",
      })
    );
    if (result.code === "rest_post_invalid_page_number") {
      return setOrgs([]);
    }
    setOrgs(
      result.map((p: any) => ({
        description: p.excerpt.rendered,
        name: p.title.rendered,
        orgId: p.id as number,
        activity: activityType[p.activitytype[0]].name,
        orgType: organizationType[p.organizationtype[0]].name,
        wpsrc: p.event.mainImage?.[0],
      }))
    );
  };
  return (
    <PlasmicOrg
      orgs={
        <>
          {orgs.map((o) => (
            <OrgCard {...o} key={o.orgId} />
          ))}
        </>
      }
      searchInput={{
        value: keyword,
        onChange(e) {
          setKeyword(e.target.value);
        },
        onSubmit() {
          search();
        },
      }}
      searchButton={{
        onClick() {
          search();
        },
      }}
      resultLength={orgs.length.toString()}
      pager={
        <Pager
          hasNext={orgs.length >= PER_PAGE}
          hasPrev={page > 1}
          pageFn={(i) => setPage((p) => p + i)}
        ></Pager>
      }
    />
  );
}

export default Org;
