// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import React, { useState, useEffect } from "react";
import OrgCard from "../components/OrgCard";
import { PlasmicOrg } from "../components/plasmic/shinkan_next/PlasmicOrg";
import { activityType, organizationType } from "../utils/categoryTable";
import { s3Fetch } from "../utils/s3Fetch";

function Org() {
  const [orgs, setOrgs] = useState<
    {
      wpsrc: string;
      description: string;
      name: string;
      activity: "sports" | "art" | "culture" | "other";
      orgType: "ippan" | "kagai" | "other";
      orgId: number;
    }[]
  >([]);

  const [input, setInput] = useState("");

  const router = useRouter();
  const keyword = router.query.q || "";
  useEffect(() => {
    (async () => {
      if (keyword.length === 0) {
        return setOrgs([]);
      }

      const result = await s3Fetch("/search/org?q=" + keyword);

      if (result.code === "rest_post_invalid_page_number") {
        return setOrgs([]);
      }
      setOrgs(
        result.map((p: any) => ({
          description: p.excerpt.rendered,
          name: p.title.rendered,
          orgId: p.id as number,
          activity: activityType[p.activitytype[0]]?.name,
          orgType: organizationType[p.organizationtype[0]]?.name,
          wpsrc: p.event.mainImage?.[0],
        }))
      );
    })();
  }, [keyword]);

  const search = async () => {
    router.push({
      pathname: "/org",
      query: {
        q: input || undefined,
      },
    });
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) =>
    e.keyCode === 13 && search(); // 日本語環境は時代が遅れており、keyCodeを使わないと変換確定なのか、検索したいのかが判定できない

  return (
    <PlasmicOrg
      orgs={
        <>
          {orgs.map((o) => (
            <OrgCard {...o} key={o.orgId} />
          ))}
        </>
      }
      searchInput={{
        value: input,
        onChange(e) {
          setInput(e.target.value);
        },
        onKeyDown,
      }}
      searchButton={{
        onClick() {
          search();
        },
      }}
      resultLength={orgs.length.toString()}
      pager={<></>}
    />
  );
}

export default Org;
