name: Build Exported
on:
  push:
    branches:
      - "release"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install deps
        run: npm ci
      - name: replace path
        run: sed -ri 's/\/plasmic\/shinkan_next\/images/\/\~shinkan-web\/plasmic\/shinkan_next\/images/g' $(find components -type f)
      - name: set .env file
        run: echo -ne "NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=UA-162922927-1\nNEXT_PUBLIC_BASEPATH=/~shinkan-web" > .env.local
      - name: build & export
        run: npx next build && npx next export
      - name: duplicate dirs
        run: |
          cd out/org
          for id in ./*.html; do
            mkdir ${id:2:-5}
            cp $id ${id:2:-5}/index.html
          done
          cp ../org.html ./index.html
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out

      - name: install sshpass
        run: sudo apt-get -y install sshpass
      - name: upload to server
        run: sshpass -e scp -o StrictHostKeyChecking=no -r out/* shinkan-web@www.stb.tsukuba.ac.jp:.
        env:
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
